### PR TITLE
Installation instructions for the README

### PR DESCRIPTION
**Pull request by tolleiv**
Hi,
I haven't used TypeScript yet and others might also have issues running the app, that's why I'd suggest to have some installation instructions in the README. Here's what I kept as installation protocol to run it on a Raspian / Debian Jessie. I assume that this can be simplified when using the TypeScript tools properly.
Cheers

### CODE REVIEW

**Comment by hansmbakker** [comment]
Hi,
cool that you're picking up development of this package! However personally I'm not planning to work on it soon as I'm currently focussing on other things (like .Net SDK for Nuimo, Windows IoT Core Hub for Nuimo).
I hope it is useful for you though.

As for the installation instructions: I think you don't have to do `sudo npm install -g typings` and `typings install ...` anymore.

This has been replaced by
```
npm install --save @types/node
```

**Comment by tolleiv** [comment]
Don't worry - that's fine for me. I'm also just experimenting with the Nuimo and MQTT and just kept my habit to contribute all adjustments which I made anyways. They might not be useful for you, but maybe for others.

**Comment by craigdent** [comment]
Did you get any further with this @tolleiv ?

Did you get it working with home assistant the nuimo device or with the hub?

**Comment by tolleiv** [comment]
@craigdent well all I did was contributed back via Pull-Requests. I think it worked fine for me back then. I stopped using Nuimo for other reasons but the setup based on that nuimo-mqtt-manager worked just fine.

**Comment by craigdent** [comment]
Oh righto

Why did you give up on it or not using it now still?

Did you get the hub too?

I’ve had mine sitting on a shelf for last few years. Want to get it working with home assistant or homebridge

I’ve got the nuimo control + hub. Such a waste since haven’t been able to integrate with anything

**Pull request closed without merging**
